### ISSUE TITLE
[error] (common/*:update) sbt.ResolveException: unresolved dependency:

### ISSUE THREAD

**Issue by vitalyte** [adrianhurt/play-multidomain-auth#2]
HEAD, play_bootstrap3-0_4-snapshot
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.adrianhurt#play-bootstrap3_2.11;0.4-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last common/*:update for the full output.
[error] (common/*:update) sbt.ResolveException: unresolved dependency: com.adria
nhurt#play-bootstrap3_2.11;0.4-SNAPSHOT: not found
[error] Total time: 20 s, completed 13 схЁ. 2015 23:47:17
==> change line
		"com.adrianhurt" %% "play-bootstrap3" % "0.4"	// Add bootstrap3 helpers and field constructors (http://play-bootstrap3.herokuapp.com/)

and it help

thanks for nice work

**Comment by adrianhurt** [comment]
Thanks! It's now corrected
