### ISSUE TITLE
upgrade to play 2.4 and silhouette 3

### ISSUE THREAD

**Issue by Enalmada** [adrianhurt/play-multidomain-auth#3]
This example seems exactly what the community needs to get up and running on silhouette.  Could someone who knows silhouette upgrade this amazing foundation for those just starting out?

**Comment by adrianhurt** [comment]
Sorry but now I don't have time to learn about the version 3 of Silhouette. I should, I know. In fact, I should upgrade it for my own project. But for the moment I can't :(  But of course, any PR will be welcomed!!

**Comment by Enalmada** [comment]
By the way, this project exposed me several ways of doing things better including play-bootstrap3 which is jaw dropping awesome.  Thanks so much for your community contributions.

**Comment by adrianhurt** [comment]
Thank you so much. I'm glad it could be useful.

**Comment by reneerojas** [comment]
I was trying to do the same, but after some hours with a lot of erros and since both, play and silhouette changed a lot including core concepts. I start to ask myself if not will be easier take the new silhouette template and refactoring this code to play 2.4 project. What you think about this?

**Comment by adrianhurt** [comment]
Yes, I need time to check the new version of Silhouette but it seems to be very different. So I suppose it would be necessary a complete refactor. If any of you make a new stable fork I will link it from the top of _readme_. If you prefer to make a PR I will try to check it but I don't have a lot of time for the moment, so maybe it would be frozen for a long period if there are many changes.

Thanks

**Comment by adrianhurt** [comment]
For the moment, I've just updated the base project [play-multidomain-seed](https://github.com/adrianhurt/play-multidomain-seed) to Play 2.4

**Comment by glidester** [comment]
Hi, I've tried to refactor this project too but I've hit a dead end. My version compiles and runs but for some reason the web module routes are not available (only the admin ones get listed in the 404 screen).

I was hoping to use this project as a learning guide as I'm looking to create a multi-domain authenticated site soon at work. If I can't fix the issues in my fork of this project (https://github.com/glidester/play-multidomain-auth) then I'll have to try and modify the play-multidomain-seed project instead.

Many thanks

**Comment by adrianhurt** [comment]
I apologize for not be able to maintain this project at the moment. I don't have too much free time and I'm now trying to publish another useful template, and I have also to update the [play-bootstrap3](http://play-bootstrap3.herokuapp.com) plugin to be working for Bootstrap 4. When I finish them I will try to update this project as well, but it will take me a while… Sorry for that, but I try to publish templates and examples of what I'm doing at that moment, and for this case I don't have time to spend in Silhouette right now.

Meanwhile, I think it's better to start from the play-multidomain-seed project and integrate to it the auth layer for the new version of Silhouette. You could use this project as a reference, but I don't really know how much Silhouette has changed.

**Comment by adrianhurt** [comment]
Sorry for the delay. But at the end I got some time. I've just updated to Play 2.4 and Silhouette 3.0.

In addition, there is another template only for the Silhouette but without multidomain ([Play Silhouette Credentials Seed](https://github.com/adrianhurt/play-silhouette-credentials-seed))
