### ISSUE TITLE
BindException when run via "activator ui"

### ISSUE THREAD

**Issue by CodeCombiner** [adrianhurt/play-multidomain-auth#4]
Hey Adrian!

First of all thanks a lot for nice seed project!
I have an issue when running all projects on Ubuntu 14.04
When I try to run via "activator run" everything works fine but when I try to run via "activator ui" it asks to addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.3.9") and then compiles well. But when project starts to run and netty tries to deploy, then only 1st named or 1st compiled project deploys successfully and works fine but console gives following error concerning 2nd project deployment:

background log: info:
background log: info: --- (Running the application, auto-reloading is enabled) ---
background log: info:
background log: error: Play fork run has failed due to:
background log: error: java.lang.reflect.InvocationTargetException
background log: error: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
background log: error: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
background log: error: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
background log: error: at java.lang.reflect.Method.invoke(Method.java:497)
background log: error: at play.runsupport.Reloader$.startDevMode(Reloader.scala:197)
background log: error: at play.forkrun.ForkRun$.startServer(ForkRun.scala:82)
background log: error: at play.forkrun.ForkRun.run(ForkRun.scala:173)
background log: error: at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:162)
background log: error: at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
background log: error: at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:148)
background log: error: at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
background log: error: at akka.actor.ActorCell.invoke(ActorCell.scala:487)
background log: error: at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
background log: error: at akka.dispatch.Mailbox.run(Mailbox.scala:221)
background log: error: at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
background log: error: at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
background log: error: at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
background log: error: at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
background log: error: at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
background log: error: Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
background log: error: at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
background log: error: at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:138)
background log: error: at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:135)
background log: error: at scala.Option.map(Option.scala:145)
background log: error: at play.core.server.NettyServer.(NettyServer.scala:135)
background log: error: at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:320)
background log: error: at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:318)
background log: error: at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
background log: error: at play.core.server.NettyServer$.mainDev(NettyServer.scala:317)
background log: error: at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:313)
background log: error: at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
background log: error: ... 19 more
background log: error: Caused by: java.net.BindException: Address already in use
background log: error: at sun.nio.ch.Net.bind0(Native Method)
background log: error: at sun.nio.ch.Net.bind(Net.java:437)
background log: error: at sun.nio.ch.Net.bind(Net.java:429)
background log: error: at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
background log: error: at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
background log: error: at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
background log: error: at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
background log: error: at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
background log: error: at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
background log: error: at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
background log: error: at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
background log: error: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
background log: error: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
background log: error: at java.lang.Thread.run(Thread.java:745)

Adrian , could you suggest, please, nice IDE to work with multi module projects.

**Comment by adrianhurt** [comment]
Hi @al11al I don't understand exactly how you are running the projects. In dev method using run, you only have to execute run for the whole project, and it should work all the subproject at the same time. Could you explain all the steps and commands you execute?

About the IDE, I use simply TextMate + iTerm.

**Comment by al11al** [comment]
Ok, I will explain step by step.
1. Download repository
2. Run activator 1.3.5
3. Open project in activator
4. Compile and Run
5. I get BindException

When run project the way you described everything works well. But I wanted to use any IDE for development, so I tried activator UI to export project and first run it.

**Comment by adrianhurt** [comment]
Ok, I understand. But then I don't know how to help you. Anyway, I'm now trying to update the __play-multidomain-seed__ project for Play 2.4, and the version of Silhouette used for this project is very old. So for the moment take this project only to understand some of the clues for multiprojects in Play.

**Comment by al11al** [comment]
@adrianhurt , it seems I got multiprojects now, I have successfully opened it in IDEA 15, it work fast enough. But now I have another trouble :) : 
 After I import to IDEA clean code and run it via IDEA tools all domains say 
RuntimeException: smtp.host needs to be set in application.conf in order to use this plugin (or set smtp.mock to true)

I even totally disabled pluigin and other imports but error the same. I tried all smtp setting that exist)) Here is full trace.

RuntimeException: smtp.host needs to be set in application.conf in order to use this plugin (or set smtp.mock to true)

java.lang.RuntimeException: smtp.host needs to be set in application.conf in order to use this plugin (or set smtp.mock to true)
     play.api.libs.mailer.CommonsMailerPlugin$$anonfun$5.apply(MailerPlugin.scala:46)
     play.api.libs.mailer.CommonsMailerPlugin$$anonfun$5.apply(MailerPlugin.scala:46)
     scala.Option.getOrElse(Option.scala:120)
     play.api.libs.mailer.CommonsMailerPlugin.mailerInstance$lzycompute(MailerPlugin.scala:46)
     play.api.libs.mailer.CommonsMailerPlugin.mailerInstance(MailerPlugin.scala:42)
     play.api.libs.mailer.CommonsMailerPlugin.onStart(MailerPlugin.scala:66)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
     scala.collection.immutable.List.foreach(List.scala:383)
     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.api.Play$.start(Play.scala:90)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
     scala.Option.map(Option.scala:145)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
     scala.util.Success.flatMap(Try.scala:230)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
     scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
     scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by adrianhurt** [comment]
Hi @CodeCombiner, I hope you resolve your problems. I write you to say you I've just updated the template to Play 2.4 and Silhouette 3.0. I close this issue as well.

**Comment by CodeCombiner** [comment]
Hi @adrianhurt , thank you for notifying. I have solved the problem at the moment. The update is cool!
